clc;
clear;
close all;

a = 20;
b = 45;
ZL = a+1i*b;
disp(['ZL = ',num2str(ZL),'ohm']);
a1 = 50;
b1 = 0;
Z0 = a1 + 1i*b1;
disp(['Z0 = ',num2str(Z0),'ohm']);
f = 2e6;
L = 30;
u = 1.8e8;
disp(['f = ', num2str(f), 'Hz']);
disp(['L = ', num2str(L), 'm']);
disp(['u = ', num2str(u), 'm/s']);
disp(['Lamda = ', num2str(u/f), 'm']);
rc = (ZL-Z0)/(ZL+Z0);
rc = abs(rc);
disp(['The Voltage reflection coefficient is ', num2str(rc)]);
rc = (ZL-Z0)/(ZL+Z0);
x = real(rc);
y = imag(rc);
q = sqrt(x^2 + y^2);
VSWR = (1+q)/(1-q);
disp(['The VSWR is ',num2str(VSWR)]);
zx = Z0*((ZL+1i*Z0*tan((2*pi)/3))/(Z0+1i*ZL*tan((2*pi)/3)));
disp(['The Zx from the load ZL is ', num2str(zx),'ohm']);